# ─────────────────────────────────────────────────────────────────────────────
# SonarCloud – Configuration monorepo MicroCRM
# Back-end Java (Gradle) + Front-end Angular (TypeScript)
# ─────────────────────────────────────────────────────────────────────────────

sonar.projectKey=${SONAR_PROJECT_KEY}
sonar.organization=${SONAR_ORGANIZATION}

# Sources analysées
sonar.sources=back/src/main,front/src
sonar.tests=back/src/test,front/src

# Exclusions
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/.gradle/**

# Back-end Java
sonar.java.source=17
sonar.java.binaries=back/build/classes
sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml

# Front-end TypeScript
sonar.typescript.lcov.reportPaths=front/coverage/microcrm/lcov.info
